config/routes.rb
# frozen_string_literal: true

using GraphQL::Pro::Routes

Rails.application.routes.draw do
  post '/ageroapi/authcode' => 'agero_webhook#auth_code'

  post "/graphql", to: "graphql#execute"
  post "/graphql/batch", to: "graphql#batch"

  if Rails.env.development?
    post "/graphql/webhook", to: "graphql#fake_webhook"
  end
  graphql_dashboard = Rack::Builder.new do
    use(Rack::Auth::Basic) do |username, password|
      username == ENV.fetch("GRAPHQL_DASHBOARD_USERNAME") && password == ENV.fetch("GRAPHQL_DASHBOARD_PASSWORD")
    end
    run SwoopSchema.dashboard
  end

  mount graphql_dashboard, at: "/graphql/dashboard"
  mount SwoopSchema.operation_store_sync, at: "/graphql/sync"
  # Handle webhooks for subscriptions:
  mount SwoopSchema.ably_webhooks_client, at: "/ably/webhooks"
  post '/ably/auth' => 'ably#auth'

  require 'sidekiq_unique_jobs/web'
  # fix sessions in sidekiq so that the web interface doesn't throw csrf errors, see
  # https://github.com/mperham/sidekiq/wiki/Monitoring#forbidden
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
  mount Sidekiq::Web => "/sidekiq"

  # QBD

  get '/t/:uuid' => 'callbacks#txt'

  constraints(host: /farmerssurvey.com/) do
    match "/(*path)" => redirect { |params, req| "http://farmers.com" }, :via => [:get, :post]
  end

  # Redirect www -> naked
  constraints(host: /^www\./i) do
    match '(*any)' => redirect { |params, request|
      URI.parse(request.url).tap { |uri| uri.host.sub!(/^www\./i, '') }.to_s
    }, :via => [:get, :post]
  end

  use_doorkeeper

  get '/stats(.json)' => "health_check#index"

  get '/txt/:uuid' => 'callbacks#txt'

  post '/twilio_status/:audit_id' => 'callbacks#twilio_status'

  # begin react endpoints
  root to: 'react#application'

  if Rails.env.development?
    get '/dev(/*dev)' => 'react#dev'
    get '/survey' => 'react#dev_survey'
    get '/pdf' => 'invoice_pdfs#pdf'
  end
  # end react endpoints

  controller :consumer_mobile_web do
    get '/get_location/:uuid', action: :get_location
    get '/show_eta/:uuid', action: :show_eta
    get '/s/:uuid', action: :survey
  end

  get '/ticket/:invoice_uuid(/:id)', to: 'invoice_pdfs#show', as: "invoice_pdf"

  # TODO why do we expose this?
  get '/time' => 'welcome#time'

  get '/apple-app-site-association', to: 'welcome#apple_app_site_association'
  get '/.well-known/apple-app-site-association', to: 'welcome#apple_app_site_association'
  get '/.well-known/assetlinks', to: 'welcome#assetlinks'

  post '/review/callback' => 'callbacks#review_callback'
  get '/review/:uuid' => 'callbacks#review_redirect'
  get '/r/:fleet/:uuid' => 'callbacks#review_redirect'

  # API
  namespace :api, constraints: { format: 'json' }, defaults: { format: :json } do
    post 'issc/event' => 'issc_webhook#create'

    controller :digital_dispatch_webhooks do
      post 'digital_dispatch/handle_rsc_event', action: :handle_rsc_event
    end

    namespace :v1 do
      post '/sites/search' => 'sites#search'

      get 'service_aliases' => 'service_aliases#index'

      resources :roles, only: [:index]

      get '/departments/batch' => 'departments#batch'
      resources :departments

      get '/tags/batch' => 'tags#batch'
      resources :tags

      get '/poi_sites/batch' => 'poi_sites#batch'
      resources :poi_sites

      get 'tire_types/batch' => 'tire_types#batch'
      get 'symptoms/standard' => 'symptoms#standard'
      get 'symptoms/batch' => 'symptoms#batch'
      post 'symptoms/change' => 'symptoms#change'

      get '/customer_types/batch' => 'customer_types#batch'

      post '/jobs/:job_id/audit_job_statuses' => 'audit_job_statuses#create'

      get 'job_status_reason_types' => 'job_status_reason_types#index'

      resources :oauth_applications, only: [:index, :create, :destroy]

      get 'referers' => 'referers#index'

      namespace :fleet do
        get 'jobs/active' => 'jobs#active'
        get 'jobs/map' => 'jobs#map'
        get 'jobs/done' => 'jobs#done'
        get 'jobs/:id/recommended_providers' => 'jobs#recommended_providers'
        get 'jobs/:id/recommended_providers/:provider_id' => 'jobs#recommended_provider'
        post 'jobs/:id/copy' => 'jobs#copy'
        patch 'jobs/:id/status' => 'jobs_status#update'
        patch 'jobs/:id/choose_partner' => 'jobs_choose_partner#update'
        post 'jobs/:id/send_details_email' => 'jobs#send_details_email'

        get '/jobs/search_new' => 'job_search#index'
        get '/users/search' => 'user_search#index'
        get '/providers/search' => '/api/v1/fleet/search/provider_search#index'

        get '/issues' => 'issues#index'

        get 'jobs/vin/:vin' => 'jobs#show'
        resources :jobs do
          patch 'change_provider_to/:new_rescue_provider_id', to: 'jobs#change_provider_to'
          patch 'change_payment_type_to/:new_payment_type_id', to: 'jobs#change_payment_type_to'

          resources :attached_documents, only: [:create, :update] do
            collection do
              get 'presign'
            end
          end

          resources :explanations, only: [:create, :update]
        end

        get 'partial_jobs' => 'partial_jobs#index'

        resources :sites

        get 'symptoms' => 'symptoms#index'
        get 'rescue_vehicles' => 'vehicles#index'
        get 'rescue_vehicles/batch' => 'vehicles#batch'

        post 'inventory_items' => 'inventory_items#create'
        delete 'inventory_items/:id' => 'inventory_items#destroy'
        get 'inventory_items/tires' => 'inventory_items#tires'
        get 'inventory_items/tire_quantity_by_site_and_type' => 'inventory_items#tire_quantity_by_site_and_type'
        patch 'inventory_items/decrease_tire_quantity' => 'inventory_items#decrease_tire_quantity'
        get 'inventory_items/:id' => 'inventory_items#show'
        patch 'inventory_items/:id' => 'inventory_items#update'

        ### DEPRECATED: These routes are deprecated and should be moved over to the below rescue_companies routes
        post 'companies' => 'rescue_companies#create'
        get 'companies/batch' => 'rescue_companies#batch'
        get 'company/logo/presign' => 'rescue_companies#presign'
        post 'company/logo' => 'rescue_companies#create_logo'
        delete 'company/logo' => 'rescue_companies#delete_logo'
        get "companies/:id" => "rescue_companies#show"
        post 'companies/site' => 'rescue_companies#add_site_to_existent_partner'
        post "companies/existing_site" => "rescue_companies#add_existing_site"
        ### End deprecated routes

        get '/search/rescue_companies/:term' => 'rescue_companies#search_rescue_companies'
        post 'rescue_companies' => 'rescue_companies#create'
        get 'rescue_companies/batch' => 'rescue_companies#batch'
        get 'rescue_company/logo/presign' => 'rescue_companies#presign'
        post 'rescue_company/logo' => 'rescue_companies#create_logo'
        delete 'rescue_company/logo' => 'rescue_companies#delete_logo'
        get "rescue_companies/:id" => "rescue_companies#show"
        post 'rescue_companies/site' => 'rescue_companies#add_site_to_existent_partner'
        post "rescue_companies/existing_site" => "rescue_companies#add_existing_site"

        get 'customer_types' => 'customer_types#index'

        post 'invoices/download' => 'invoices#download'

        get 'invoices' => 'invoices#index'
        get 'invoices_search' => 'invoices#search'
        patch 'invoices/:id' => 'invoices#update'

        # DEPRICATED (can be removed after VendorID Rates FE is shipped)
        # use rates/fetch_by_filters route instead
        get 'rates/provider/:rescue_provider_id/service/:service_code_id' => 'rates#provider'
        get 'rates/fetch_by_filters' => 'rates/fetch_by_filters'

        # DEPRICATED (can be removed after VendorID Rates FE is shipped)
        # route is deprecated, use 'rates/defaults' instead
        post "rates/provider/:rescue_provider_id/services/:service_code_id" => "rates#create_service"
        post 'rates/defaults' => 'rates#create_based_on_defaults'

        post '/rates/live' => 'rates#live'
        patch 'rates' => 'rates#update_multi'
        post 'rates' => 'rates#create'
        delete 'rates' => 'rates#delete'
        # get 'rates/provider/:rescue_provider_id/addons' => 'rates#addons'

        get 'reports' => 'reports#index'
        post 'reports/:id/run(.:report_format)' => 'reports#run_report'

        get 'report_results/:id' => 'report_results#show'

        # DEPRICATED (can be removed after VendorID Rates FE is shipped)
        # use services/by_rates_filter route instead
        get 'services/with_rates/provider/:rescue_provider_id' => 'services#with_rates_by_provider'
        get 'services/by_rates_filter' => 'services#index_by_rates_filter'

        get 'services/partner/:provider_id' => 'services#partner'
        get 'services/standard' => 'services#standard'
        post "sites/search" => "sites#search"

        resources :invoice_rejections, only: [:index, :create] do
          collection do
            get :reasons
          end
        end

        get "vehicle_categories/partner/:rescue_provider_id" => "vehicle_categories#partner"

        post 'look' => 'looker#look'
        get 'looker/dashboards' => 'looker#dashboards'

        post 'autocomplete/rescue_companies_by_provider' => 'autocomplete#rescue_companies_by_provider'
        post 'autocomplete/rescue_providers' => 'autocomplete#rescue_providers'
        post 'autocomplete/recommended_providers' => 'autocomplete#recommended_providers'

        # Depricated, use /policy/search
        post '/policy' => 'pcc/policy#create'

        # New Policy Search routes
        # { job_id:<job.id>, search: {policy_number:<policy_num>}}
        post '/policy/search' => 'pcc/policy#search'

        get  '/policy/:id' => 'pcc/policy#show'
        get  '/policy/:policy_id/pcc_vehicle/:pcc_vehicle_id/pcc_driver/:pcc_driver_id/coverage' => 'pcc/policy#show_coverage'

app/models/invoice_pdf.rb
# frozen_string_literal: true

class InvoicePdf < BaseModel

  belongs_to :invoice

  def populate_public_url
    self.public_url = s3_public_url
  end

  def s3_object
    s3_bucket.object(s3_object_key)
  end

  def s3_public_url
    s3_object.public_url.to_s
  end

  def url_for(read_or_write, response_options = {})
    s3_object.presigned_url(:get, response_options.merge(expires_in: S3_SIGNED_URL_EXPIRATION))
  end

  private

  def s3_bucket_name
    Configuration.s3.invoice_bucket
  end

  def s3_bucket
    S3.bucket(s3_bucket_name)
  end

  def s3_object_key
    "#{invoice.job_id}-#{invoice.uuid}-#{id}.pdf"
  end

end

app/controllers/invoice_pdfs_controller.rb
# frozen_string_literal: true

class InvoicePdfsController < ApplicationController

  def show
    @invoice = Invoice.find_by!(uuid: params[:invoice_uuid])
    @attempts = params[:attempts].to_i
    @attempts += 1

    if params[:id]
      @invoice_pdf = InvoicePdf.find(params[:id])

      if params[:poll]

        # uuid/timestamp?poll=true not ready
        if @invoice_pdf.public_url.blank?
          render :show, layout: false

        # uuid/timestamp?poll=true ready
        else
          redirect_to @invoice_pdf.url_for(:read, response_content_disposition: 'inline').to_s
        end

      # uuid/id not polling, direct link
      else
        redirect_to @invoice_pdf.url_for(:read, response_content_disposition: 'inline').to_s
      end
    else
      @invoice_pdf = @invoice.generate_pdf
      render :show, layout: false
      # render text: "still working, reply with timestamp: #{invoice_pdf.id}"
    end
  end

  ##
  # The following action at '/pdf' is used for generating a test pdf in development
  # you can request a specific PDF using '/pdf?id=num'
  def pdf
    pdf_id = params[:id].to_i
    respond_to do |format|
      invoice = pdf_id > 0 ? Invoice.find_by(id: pdf_id) : Invoice.first
      sender_name = nil
      if invoice.sender && invoice.sender.name?
        sender_name = invoice.sender.name
      end
      locals = { invoice: invoice, job: invoice.job, sender_name: sender_name, scale_factor: 4.5 }
      format.pdf do
        render pdf: "file_name",
               locals: locals,
               template: 'pdfs/invoice.pdf.erb',
               footer: {
                 font_name: 'Open Sans',
                 font_size: 8,
                 left: 'Powered by Swoop',
                 right: '([page] of [topage])',
               }
      end

      format.html do
        render "pdfs/invoice.pdf", layout: nil, locals: locals
      end
    end
  end

end

app/views/invoice_pdfs/show.html.erb
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <script>
      // REOLADS WITH NEW VERSION AFTER 8 SECONDS
      setTimeout(function(){
        page = '<%= invoice_pdf_url({
          invoice_uuid: @invoice.uuid,
          id: @invoice_pdf.id,
          poll: true,
          attempts: @attempts
        }) %>'
        window.location.replace(page);
      }, 4000)
    </script>
    <style>
          /* Absolute Center Spinner */
      body {
        transform: scale(2);
      }
      .loading {
        position: fixed;
        z-index: 999;
        overflow: show;
        margin: auto;
        top: 50%;
        left: 50%;
        bottom: 0;
        right: 0;
        scale: 5;
      }

      /* Transparent Overlay */
      .loading:before {
        content: '';
        display: block;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0,0,0,0.3);
      }

      /* :not(:required) hides these rules from IE9 and below */
      .loading:not(:required) {
        /* hide "loading..." text */
        font: 0/0 a;
        color: transparent;
        text-shadow: none;
        background-color: transparent;
        border: 0;
      }

      .loading:not(:required):after {
        content: '';
        display: block;
        font-size: 10px;
        width: 1em;
        height: 1em;
        margin-top: -0.5em;
        -webkit-animation: spinner 1500ms infinite linear;
        -moz-animation: spinner 1500ms infinite linear;
        -ms-animation: spinner 1500ms infinite linear;
        -o-animation: spinner 1500ms infinite linear;
        animation: spinner 1500ms infinite linear;
        border-radius: 0.5em;
        -webkit-box-shadow: rgba(0, 0, 0, 0.75) 1.5em 0 0 0, rgba(0, 0, 0, 0.75) 1.1em 1.1em 0 0, rgba(0, 0, 0, 0.75) 0 1.5em 0 0, rgba(0, 0, 0, 0.75) -1.1em 1.1em 0 0, rgba(0, 0, 0, 0.5) -1.5em 0 0 0, rgba(0, 0, 0, 0.5) -1.1em -1.1em 0 0, rgba(0, 0, 0, 0.75) 0 -1.5em 0 0, rgba(0, 0, 0, 0.75) 1.1em -1.1em 0 0;
        box-shadow: rgba(0, 0, 0, 0.75) 1.5em 0 0 0, rgba(0, 0, 0, 0.75) 1.1em 1.1em 0 0, rgba(0, 0, 0, 0.75) 0 1.5em 0 0, rgba(0, 0, 0, 0.75) -1.1em 1.1em 0 0, rgba(0, 0, 0, 0.75) -1.5em 0 0 0, rgba(0, 0, 0, 0.75) -1.1em -1.1em 0 0, rgba(0, 0, 0, 0.75) 0 -1.5em 0 0, rgba(0, 0, 0, 0.75) 1.1em -1.1em 0 0;
      }

      /* Animation */

      @-webkit-keyframes spinner {
        0% {
          -webkit-transform: rotate(0deg);
          -moz-transform: rotate(0deg);
          -ms-transform: rotate(0deg);
          -o-transform: rotate(0deg);
          transform: rotate(0deg);
        }
        100% {
          -webkit-transform: rotate(360deg);
          -moz-transform: rotate(360deg);
          -ms-transform: rotate(360deg);
          -o-transform: rotate(360deg);
          transform: rotate(360deg);
        }
      }
      @-moz-keyframes spinner {
        0% {
          -webkit-transform: rotate(0deg);
          -moz-transform: rotate(0deg);
          -ms-transform: rotate(0deg);
          -o-transform: rotate(0deg);
          transform: rotate(0deg);
        }
        100% {
          -webkit-transform: rotate(360deg);
          -moz-transform: rotate(360deg);
          -ms-transform: rotate(360deg);
          -o-transform: rotate(360deg);
          transform: rotate(360deg);
        }
      }
      @-o-keyframes spinner {
        0% {
          -webkit-transform: rotate(0deg);
          -moz-transform: rotate(0deg);
          -ms-transform: rotate(0deg);
          -o-transform: rotate(0deg);
          transform: rotate(0deg);
        }
        100% {
          -webkit-transform: rotate(360deg);
          -moz-transform: rotate(360deg);
          -ms-transform: rotate(360deg);
          -o-transform: rotate(360deg);
          transform: rotate(360deg);
        }
      }
      @keyframes spinner {
        0% {
          -webkit-transform: rotate(0deg);
          -moz-transform: rotate(0deg);
          -ms-transform: rotate(0deg);
          -o-transform: rotate(0deg);
          transform: rotate(0deg);
        }
        100% {
          -webkit-transform: rotate(360deg);
          -moz-transform: rotate(360deg);
          -ms-transform: rotate(360deg);
          -o-transform: rotate(360deg);
          transform: rotate(360deg);
        }
      }
    </style>
  </head>
  <body>
    <div class="loading">Loading&#8230;</div>
  </body>
</html>